import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
    console.warn('Supabase credentials missing. Cloud features will be disabled.');
}

export const supabase = (supabaseUrl && supabaseAnonKey)
    ? createClient(supabaseUrl, supabaseAnonKey)
    : null;

// Helper to check if supabase is ready
export const isSupabaseconfigured = () => !!supabase;

export interface RecentFileDB {
    id?: string;
    user_id?: string;
    name: string;
    url?: string;
    source: 'local' | 'drive' | 'url';
    last_viewed: string;
    metadata: any;
}

// --- Auth ---
export const signInWithGoogle = async () => {
    if (!supabase) throw new Error("Supabase not configured");
    const { data, error } = await supabase.auth.signInWithOAuth({
        provider: 'google',
        options: {
            redirectTo: window.location.origin
        }
    });
    if (error) throw error;
    return data;
};

export const signOut = async () => {
    if (!supabase) return;
    const { error } = await supabase.auth.signOut();
    if (error) throw error;
};

export const getUser = async () => {
    if (!supabase) return null;
    const { data: { user } } = await supabase.auth.getUser();
    return user;
};

// --- Database (Recent Files) ---
export const getRecentFiles = async () => {
    if (!supabase) return [];
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return [];

    const { data, error } = await supabase
        .from('recent_files')
        .select('*')
        .eq('user_id', user.id)
        .order('last_viewed', { ascending: false })
        .limit(20);

    if (error) {
        console.error('Error fetching recent files:', error);
        return [];
    }
    return data as RecentFileDB[];
};

export const upsertRecentFile = async (file: Omit<RecentFileDB, 'user_id'>) => {
    if (!supabase) return;
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return;

    // Ideally we match by some unique identifier (like valid URL or drive ID)
    // For local files, we might just be logging history without deduplication unless we hash them, 
    // but for now let's just insert new entries or update if we have an ID.

    const payload = {
        ...file,
        user_id: user.id,
        last_viewed: new Date().toISOString()
    };

    const { error } = await supabase
        .from('recent_files')
        .upsert(payload, { onConflict: 'id' }); // id must be generated by client or passed if updating

    if (error) console.error('Error saving recent file:', error);
};

